- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
   - name: import VPC Variables
     include_vars: vars/vpc_setup

    
   - name: create vprofile-vpc
     ec2_vpc_net:
       name: "{{vpc_name}}"
       cidr_block: "{{vpccidr}}"
       region: "{{region}}"
       dns_support: yes
       dns_hostnames: yes
       tenancy: default
       state: "{{state}}"
     register: vpcout

   - debug:
      var: vpcout
       
   - name: creat Public subnet 1 in zone1
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"
       cidr: "{{pubsub1cidr}}"
       map_public: yes
       resources_tags:
         Name: vprofile_pubsub1
     register: pubsub1 out
      
        
       
     
